# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  #vmImage: 'windows-latest'
  name: 'Default'


steps:

- task: CmdLine@2
  inputs:
    script: 'npm install protractor -g'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  inputs:
    script: 'npm i wdio-selenium-standalone-service'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  inputs:
    script: 'webdriver-manager update  --standalone'

- task: CmdLine@2
  inputs:
    script: 'webdriver-manager start  --standalone'



    
- task: CmdLine@2
  inputs:
    script: 'protractor conf.js'
    workingDirectory: '$(Build.SourcesDirectory)'
    

    


    

  


